spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company-collaboration-platform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

server:
  port : 8081
  context-path : /api
  
cors:
  allowedOrings: '*'
