spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company-collaboration-platform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          timeout: '5000'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.gmail.com
    username: mohameddhia.hachem@esprit.tn
    password: 191SMT3919
    port: '587'

mail:
  smtp:
    debug: 'true'

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

server:
  port : 8081
  servlet:
    context-path: /api
  
cors:
  allowedOrings: '*'
